### ISSUE TITLE
建议每次merge的时候rebase一下

### ISSUE THREAD

**Issue by pusidun** [realzhaijiayu/leetcode#14]
commit log太多了没必要，一个pl一个log就够了

**Comment by realzhaijiayu** [comment]
非常感谢你的建议！用rebase的确会让历史记录更加简洁。
之前大部分时间都是在手机上操作PR，对这个问题没有那么重视，有时候不能rebase就直接偷懒merge了。
这不是一个好习惯，我再熟练一下rebase，以后尽量在电脑上完成。
欢迎多提建议！:thumbsup:

**Comment by pusidun** [comment]
@realzhaijiayu 我记得pl最后是可以选直接merge，squash还是rebase的，您可以看一下

**Comment by realzhaijiayu** [comment]
可以，不过有冲突的话就不能直接rebase
